#include QMK_KEYBOARD_H

enum planck_layers {
  _BASE,
  _LOWER,
  _RAISE,
  _ADJUST,
  _GAME,
};

#define LOWER MO(_LOWER)
#define RAISE MO(_RAISE)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT(
		   KC_ESC,   KC_Q,KC_W,KC_E,KC_R,KC_T,           KC_Y,KC_U,KC_I,KC_O,KC_P,KC_BSPACE,         KC_HOME, KC_END,KC_PGDN,KC_PGUP,
		   KC_TAB,   KC_A,KC_S,KC_D,KC_F,KC_G,           KC_H,KC_J,KC_K,KC_L,KC_SCOLON,KC_QUOTE,     KC_KP_7,KC_KP_8,KC_KP_9,KC_KP_DOT,
		   KC_LSHIFT,KC_Z,KC_X,KC_C,KC_V,KC_B,           KC_N,KC_M,KC_COMMA,KC_DOT,KC_SLASH,KC_ENTER,KC_KP_4,KC_KP_5,KC_KP_6,KC_ENTER,
		   KC_LCTRL,KC_NO,KC_LALT,KC_LGUI,LOWER,KC_SPACE,RAISE,KC_LEFT,KC_DOWN,KC_UP,KC_RIGHT,       KC_KP_1,KC_KP_2,KC_KP_3,KC_KP_0
		   ),
  [_LOWER] = LAYOUT(
		    KC_TILD,KC_EXLM,KC_AT,KC_HASH,KC_DLR,KC_PERC,KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_DELETE,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_F6,KC_UNDS,KC_PLUS,KC_LCBR,KC_RCBR,KC_PIPE,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,KC_F12,LALT(KC_F4),KC_HOME,KC_HOME,KC_END,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_MNXT,KC_VOLD,KC_VOLU,KC_MPLY,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS
		    ),
  [_RAISE] = LAYOUT(
		    KC_GRAVE,KC_1,KC_2,KC_3,KC_4,KC_5,KC_6,KC_7,KC_8,KC_9,KC_0,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_DELETE,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_F6,KC_MINUS,KC_EQUAL,KC_LBRC,KC_RBRC,KC_BSLASH,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,KC_F12,LALT(KC_F4),KC_PGDOWN,KC_PGDOWN,KC_PGUP,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_MNXT,KC_VOLD,KC_VOLU,KC_MPLY,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS
		    ),
  [_ADJUST] = LAYOUT(
		    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_DELETE,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,A(C(KC_LEFT)),A(C(KC_RIGHT)),KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,RESET,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,A(C(S(KC_LEFT))),A(C(S(KC_RIGHT))),TO(4),KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_MS_LEFT,KC_MS_DOWN,KC_MS_UP,KC_MS_RIGHT,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS
		    ),
  [_GAME] = LAYOUT(
		   KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,  KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		   KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,  KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		   KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,  KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
		   KC_TRNS,TO(0),  KC_TRNS,KC_TRNS,KC_SPACE,     LOWER,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS
),
};

uint32_t layer_state_set_user(uint32_t state) {

  state = update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
  
  // So state in this context is a layer_state
  // biton32 returns the highest set bit
  // The layers are represented as bits in state
  // BASE   0  1
  // LOWER  1  2
  // RAISE  2  4
  // ADJUST 3  8
  // GAME   4 16
  uint8_t layer = biton32(state);

  // Take care of the auto-shift
  if (layer == _GAME) {
    autoshift_disable();
    // update layer to remove the bit from the _GAME layer_state
    layer = biton32(state & ~(1 << _GAME));
  } else {
    autoshift_enable();
  }

  // Now Take care of the lights
  switch (layer) {
  case _BASE:
    break;
  case _LOWER:
    break;
  case _RAISE:
    break;
  case _ADJUST:
    break;
  }
  
  return state;
}
